video_path: ../trafficData/four lanes.mp4
output_dir: ./output
model:
  path: yolo11m.pt
  confidence: 0.2
  classes:
  - car
  - motorcycle
  - bus
  - truck
tracker:
  type: deepsort
  max_age: 20
  n_init: 2
  max_cosine_distance: 0.8
  embedder: mobilenet
lanes:
- name: Lane 1
  polygon:
  - - 0
    - 652
  - - 0
    - 719
  - - 256
    - 719
  - - 888
    - 415
  - - 694
    - 418
- name: Lane 2
  polygon:
  - - 262
    - 719
  - - 778
    - 719
  - - 1079
    - 423
  - - 892
    - 417
- name: Lane 3
  polygon:
  - - 783
    - 719
  - - 1279
    - 719
  - - 1279
    - 429
  - - 1082
    - 422
